drop table mot;
DROP PROCEDURE upd_motaltasus;

begin work; 
--Cria tabela
create table "informix".mot
(cod char(6),des varchar(60));
revoke all on "informix".mot from "public" as "informix";

--Inseri registros
INSERT INTO MOT VALUES ('11','ALTA CURADO');
INSERT INTO MOT VALUES ('12','ALTA MELHORADO');
INSERT INTO MOT VALUES ('14','ALTA A PEDIDO');
INSERT INTO MOT VALUES ('15','ALTA COM PREVISAO DE RETORNO PARA ACOMPANHAMENTO DO PACIENTE');
INSERT INTO MOT VALUES ('16','ALTA POR EVASAO');
INSERT INTO MOT VALUES ('18','ALTA POR OUTROS MOTIVOS');
INSERT INTO MOT VALUES ('19','ALTA DE PACIENTE AGUDO EM PSIQUIATRIA');
INSERT INTO MOT VALUES ('21','PERMANENCIA, POR CARACTERISTICAS PROPRIAS DA DOENCA');
INSERT INTO MOT VALUES ('22','PERMANENCIA, POR INTERCORRENCIA');
INSERT INTO MOT VALUES ('23','PERMANENCIA, POR IMPOSSIBILIDADE SOCIO-FAMILIAR');
INSERT INTO MOT VALUES ('24','PERMANENCIA, POR PROCESSO DE DOACAO DE ORGAOS, TECIDOS E CELULAS - DOADOR VIVO');
INSERT INTO MOT VALUES ('25','PERMANENCIA, POR PROCESSO DE DOACAO DE ORGAOS, TECIDOS E CELULAS - DOADOR MORTO');
INSERT INTO MOT VALUES ('26','PERMANENCIA, POR MUDANCA DE PROCEDIMENTO');
INSERT INTO MOT VALUES ('27','PERMANENCIA, POR REOPERACAO');
INSERT INTO MOT VALUES ('28','PERMANENCIA, OUTROS MOTIVOS');
INSERT INTO MOT VALUES ('31','TRANSFERIDO PARA OUTRO ESTABELECIMENTO');
INSERT INTO MOT VALUES ('32','TRANSFERENCIA PARA INTERNACAO DOMICILIAR');
INSERT INTO MOT VALUES ('41','OBITO COM DECLARACAO DE OBITO FORNECIDA PELO MEDICO ASSISTENTE');
INSERT INTO MOT VALUES ('42','OBITO COM DECLARACAO DE OBITO FORNECIDA PELO INSTITUTO MEDICO LEGAL - IML');
INSERT INTO MOT VALUES ('43','OBITO COM DECLARACAO DE OBITO FORNECIDA PELO SERVICO DE VERIFICACAO DE OBITO - SVO.');
INSERT INTO MOT VALUES ('51','ENCERRAMENTO ADMINISTRATIVO');
INSERT INTO MOT VALUES ('61','ALTA DA MAE/PUERPERA E DO RECEM-NASCIDO');
INSERT INTO MOT VALUES ('62','ALTA DA MAE/PUERPERA E PERMANENCIA DO RECEM-NASCIDO');
INSERT INTO MOT VALUES ('63','ALTA DA MAE/PUERPERA E OBITO DO RECEM-NASCIDO');
INSERT INTO MOT VALUES ('64','ALTA DA MAE/PUERPERA COM OBITO FETAL');
INSERT INTO MOT VALUES ('65','OBITO DA GESTANTE E DO CONCEPTO');
INSERT INTO MOT VALUES ('66','OBITO DA MAE/PUERPERA E ALTA DO RECEM-NASCIDO');
INSERT INTO MOT VALUES ('67','OBITO DA MAE/PUERPERA E PERMANENCIA DO RECEM-NASCIDO');
commit;

--Procedure
create procedure upd_motaltasus();
define aux_cod  like motivo_alta_sus.cod_motalta_sus;
define aux_nome like motivo_alta_sus.descricao;
define k smallint;
let k = 1;

foreach 
	select cod, des
	into aux_cod, aux_nome
	from mot;

	select count(*)
	into k
	from motivo_alta_sus
	where cod_motalta_sus = aux_cod;
	
	if k = 0 then
		insert into motivo_alta_sus(cod_motalta_sus, descricao) values(aux_cod, aux_nome);
	else
		update motivo_alta_sus set descricao = aux_nome where cod_motalta_sus = aux_cod;
	end if;
end foreach;
end procedure;

execute procedure upd_motaltasus();

drop table mot;
DROP PROCEDURE upd_motaltasus;
