delete from tm_presc_onco_ccl;
delete from tm_just_presc_onco;
delete from tm_presc_onco_ite;
delete from tm_onco_ger_ite;
delete from tb_prot_itm;
delete from tb_prot_cic;
delete from tb_prot_grp;
delete from tb_prot_cid;
delete from tb_prot_cab;