--CREATE TEMP TABLE ArqTmpCus (COD_PRD CHAR(6), ANO_MES CHAR(6)) WITH NO LOG
--INSERT INTO ArqTmpCus SELECT COD_PRD, MAX(ANO_MES) ANO_MES FROM ESHISCUS  WHERE ANO_MES <= '201110' GROUP BY COD_PRD 

SELECT FASETCAD.COD_CEL,                FACELCAD.DESCRICAO DESC_CEL,             FAPRDCAD.TIPO_PRD,
       FATIPCAD.DESCRICAO DESC_TIPO,    FAPRDCAD.CODIGO,                         FAPRDCAD.DESCRICAO,     FAPRDCAD.UNI_ESTOQU,             
       SUM(ESHISCON.QTD_CONSUMO) QTD,         
       SUM(ESHISCON.QTD_CONSUMO * ESHISCUS.CUSTO_ATU) CUSTO_ATU,                 SUM(ESHISCON.QTD_CONSUMO * ESHISCUS.CUSTO_MED) CUSTO_MED
FROM FAPRDCAD, FATIPCAD, ESHISCON, FASETCAD, OUTER FACELCAD, ESHISCUS,ArqTmpCus 
WHERE      FAPRDCAD.TIPO_PRD = FATIPCAD.TIPO_PRD 
AND        FATIPCAD.PRE_CLASS = 'MAT' 
AND        FAPRDCAD.CODIGO = ESHISCON.COD_PRD 
AND        FASETCAD.COD_SET = ESHISCON.COD_SET 
AND        FASETCAD.COD_CEL = FACELCAD.COD_CEL 
AND        ARQTMPCUS.COD_PRD = ESHISCON.COD_PRD 
AND        ESHISCUS.COD_PRD = ARQTMPCUS.COD_PRD 
AND        ESHISCUS.ANO_MES = ARQTMPCUS.ANO_MES 
AND        ESHISCON.COD_UNI = '0010' 
AND        ESHISCON.ANO_MES = '201110' 
AND        FAPRDCAD.TIPO_PRD  IN ('MED')  
AND        ESHISCON.COD_SET  IN ('0190') 
and faprdcad.codigo in('142029','323497') 
and eshiscus.cod_uni = '0010'
GROUP BY FAPRDCAD.TIPO_PRD,FATIPCAD.DESCRICAO,FASETCAD.COD_CEL,  FACELCAD.DESCRICAO,FAPRDCAD.CODIGO,FAPRDCAD.DESCRICAO,FAPRDCAD.UNI_ESTOQU  
ORDER BY FAPRDCAD.TIPO_PRD,FASETCAD.COD_CEL,FAPRDCAD.CODIGO 





SELECT PARAMETROS_MXM.VALOR AS UNIDADE,     SETOR_CTCUSTO.COD_CTCUSTO,    
       DE_PARA_IQ_TPRDCTB.CONTA_CTB_DEB,    DE_PARA_IQ_TPRDCTB.CONTA_CTB_CRE,    
       --SUM(ESHISCUS.CUSTO_MED * ESHISCON.QTD_CONSUMO) VALOR  
ESHISCUS.CUSTO_MED, ESHISCON.*
FROM   ESHISCON,    FAPRDCAD,    ESHISCUS,    FASETCAD,    FACELCAD,    SETOR_CTCUSTO,    DE_PARA_IQ_TPRDCTB,    PARAMETROS_MXM  
WHERE FASETCAD.COD_SET = ESHISCON.COD_SET
AND FACELCAD.COD_CEL = FASETCAD.COD_CEL
AND FAPRDCAD.CODIGO = ESHISCON.COD_PRD    
AND ESHISCUS.ANO_MES = ESHISCON.ANO_MES
AND ESHISCUS.COD_PRD = ESHISCON.COD_PRD
AND ESHISCUS.COD_UNI = ESHISCON.COD_UNI
AND ESHISCON.COD_SET = SETOR_CTCUSTO.COD_SET
AND FAPRDCAD.TIPO_PRD = DE_PARA_IQ_TPRDCTB.TIPO_PRD
AND ESHISCON.ANO_MES = '201110'
AND FACELCAD.COD_UNIDADE = '0010'
AND ESHISCON.QTD_CONSUMO <> '0'
AND DE_PARA_IQ_TPRDCTB.tipo_prd = 'MED'
AND SETOR_CTCUSTO.cod_set = '0190'
AND DE_PARA_IQ_TPRDCTB.conta_ctb_deb <> ''
AND FACELCAD.COD_UNIDADE = PARAMETROS_MXM.COD_UNI
AND PARAMETROS_MXM.COD_PARAMETRO = 'exp_amil_cod_emp_compradora'
GROUP BY    PARAMETROS_MXM.VALOR,    SETOR_CTCUSTO.COD_CTCUSTO,    DE_PARA_IQ_TPRDCTB.CONTA_CTB_DEB,    DE_PARA_IQ_TPRDCTB.CONTA_CTB_CRE, ESHISCUS.CUSTO_MED, ESHISCON.cod_uni,ESHISCON.cod_set,ESHISCON.cod_prd,ESHISCON.ano_mes,ESHISCON.qtd_consumo
ORDER BY    PARAMETROS_MXM.VALOR,    SETOR_CTCUSTO.COD_CTCUSTO 

SELECT * FROM ESHISCUS WHERE COD_PRD = '142029'  AND COD_UNI = '0012' ORDER BY 3 DESC --AND ANO_MES = '201110'  
SELECT * FROM ESHISCON WHERE  COD_PRD = '142029' AND COD_SET = '0190' --and ANO_MES = '201110' 

SELECT B.* FROM ESMOVCAD A, ESMOVITE B WHERE A.DOCUMENTO = B.DOCUMENTO AND A.TIPO_DOCUMENTO = B.TIPO_DOCUMENTO
AND A.DATA_MOV BETWEEN '2011-10-01' AND '2011-10-31'
AND B.COD_PRD IN ('142029','323497') AND A.SET_CON = '0190'






SELECT    PARAMETROS_MXM.VALOR AS UNIDADE,    SETOR_CTCUSTO.COD_CTCUSTO,    DE_PARA_IQ_TPRDCTB.CONTA_CTB_DEB,    
          DE_PARA_IQ_TPRDCTB.CONTA_CTB_CRE,   SUM(ESHISCUS.CUSTO_MED * ESHISCON.QTD_CONSUMO) VALOR  
FROM    ESHISCON,    FAPRDCAD,    ESHISCUS,    FASETCAD,    FACELCAD,    SETOR_CTCUSTO,    DE_PARA_IQ_TPRDCTB,    PARAMETROS_MXM  
WHERE    (FASETCAD.COD_SET = ESHISCON.COD_SET)    
AND (FACELCAD.COD_CEL = FASETCAD.COD_CEL)    
AND (FAPRDCAD.CODIGO = ESHISCON.COD_PRD)    
AND (ESHISCUS.ANO_MES = ESHISCON.ANO_MES)    
AND (ESHISCUS.COD_PRD = ESHISCON.COD_PRD)    
AND (ESHISCUS.COD_UNI = ESHISCON.COD_UNI)    
AND (ESHISCON.COD_SET = SETOR_CTCUSTO.COD_SET)    
AND (FAPRDCAD.TIPO_PRD = DE_PARA_IQ_TPRDCTB.TIPO_PRD)    
AND (ESHISCON.ANO_MES = '201110')    
AND (FACELCAD.COD_UNIDADE = '0010')    
AND (ESHISCON.QTD_CONSUMO <> 0)    
AND (FACELCAD.COD_UNIDADE = PARAMETROS_MXM.COD_UNI)                 and DE_PARA_IQ_TPRDCTB.tipo_prd = 'MED'
AND (PARAMETROS_MXM.COD_PARAMETRO = 'exp_amil_cod_emp_compradora')  and DE_PARA_IQ_TPRDCTB.CONTA_CTB_DEB <> '' and setor_ctcusto.cod_set = '0190'
GROUP BY    PARAMETROS_MXM.VALOR,    SETOR_CTCUSTO.COD_CTCUSTO,    DE_PARA_IQ_TPRDCTB.CONTA_CTB_DEB,    DE_PARA_IQ_TPRDCTB.CONTA_CTB_CRE  
ORDER BY    PARAMETROS_MXM.VALOR,    SETOR_CTCUSTO.COD_CTCUSTO 