SELECT '' AS HIST, '' AS COR,         TE_ALERTA_TRIAG.COD_PESO,         
CASE CHAR_LENGTH(CAST(TB_SEL_SENHA_FILA.NU_SENHA AS VARCHAR(10)))            WHEN 1 THEN '000'||TB_SEL_SENHA_FILA.NU_SENHA            WHEN 2 THEN '00'||TB_SEL_SENHA_FILA.NU_SENHA            WHEN 3 THEN '0'||TB_SEL_SENHA_FILA.NU_SENHA         ELSE CAST (TB_SEL_SENHA_FILA.NU_SENHA AS VARCHAR(10)) END NU_SENHA,         
CASE WHEN  (TB_SEL_SENHA_FILA.FK_COD_PAC IS NULL OR TB_SEL_SENHA_FILA.FK_COD_PAC = '') THEN         CASE WHEN(TM_CARGA_BENEF.NM_BENEFICIARIO IS NULL) THEN         CASE WHEN (TB_PAC_TRIAGEM.NO_PACIENTE IS NULL OR TB_PAC_TRIAGEM.NO_PACIENTE = '') THEN              ('PACIENTE SENHA ' || ' - ' || CASE CHAR_LENGTH(CAST(TB_SEL_SENHA_FILA.NU_SENHA AS VARCHAR(10)))              WHEN 1 THEN '000'||TB_SEL_SENHA_FILA.NU_SENHA WHEN 2 THEN '00'||TB_SEL_SENHA_FILA.NU_SENHA              WHEN 3 THEN '0'||TB_SEL_SENHA_FILA.NU_SENHA ELSE CAST (TB_SEL_SENHA_FILA.NU_SENHA AS VARCHAR(10))END)              ELSE TB_PAC_TRIAGEM.NO_PACIENTE END ELSE TM_CARGA_BENEF.NM_BENEFICIARIO END         ELSE FAPRTCAD.NOME_PAC END AS NO_PACIENTE,         TB_SEL_SENHA_FILA.DH_RETIRADA,         FAESPCAD.DESCRICAO,         CASE TB_SEL_SENHA_FILA.QT_CHAMADO            WHEN 1 THEN TE_STATUS_TRIAG.DS_STATUS || ' - ' ||  TB_SEL_SENHA_FILA.QT_CHAMADO            WHEN 2 THEN TE_STATUS_TRIAG.DS_STATUS || ' - ' ||  TB_SEL_SENHA_FILA.QT_CHAMADO            WHEN 3 THEN TE_STATUS_TRIAG.DS_STATUS || ' - ' ||  TB_SEL_SENHA_FILA.QT_CHAMADO         ELSE TE_STATUS_TRIAG.DS_STATUS         END,         TB_SEL_SENHA_FILA.QT_CHAMADO, TB_SEL_SENHA_FILA.FK_STRIAG,         TB_SEL_SENHA_FILA.FK_COD_UNI, TB_SEL_SENHA_FILA.FK_COD_ESP,         FAUSUCAD.NOME, TB_PAC_TRIAGEM.PK_TRIAGE,         TB_SEL_SENHA_FILA.DS_JUSTIFICATIVA,         CASE TB_PAC_TRIAGEM.SN_VIVA_CUIDADO         WHEN 'S' THEN 'SIM'          ELSE 'NAO'          END AS SN_VIVA_CUIDADO,          CASE TB_PAC_TRIAGEM.SN_VULNERAVEL             WHEN 'S' THEN 'SIM'             WHEN 'N' THEN 'NAO'             ELSE         CASE TB_SEL_SENHA_FILA.SN_PREFERENCIAL WHEN 'S' THEN 'SIM'          ELSE 'NAO' END         END AS SN_PREFERENCIAL,         
TB_SEL_SENHA_FILA.SN_PREFERENCIAL AS SN_SENHA,         
TB_SEL_SENHA_FILA.FK_COD_PAC, 
TB_SEL_SENHA_FILA.PK_SELSEN,         
FAPACCAD.COD_PRT, 
TB_PAC_TRIAGEM.FK_MATRICULA,
(SELECT DS_LOCALIDADE FROM  TM_HISTPAC WHERE TM_HISTPAC.FK_SELSEN = TB_SEL_SENHA_FILA.PK_SELSEN AND DH_HIST_FIM IS NULL) AS LOCALIZACAO,
CASE WHEN TE_ALERTA_TRIAG.COD_PESO IS NULL THEN '0' ELSE TE_ALERTA_TRIAG.COD_PESO END || CASE TB_SEL_SENHA_FILA.SN_PREFERENCIAL WHEN 'S' THEN '0' ELSE '1' END || CASE WHEN (YEAR(CURRENT) - YEAR(TB_PAC_TRIAGEM.DH_NASCIMENTO) > 60) THEN '0' ELSE '1' END || TB_SEL_SENHA_FILA.DH_RETIRADA, 
TB_SEL_SENHA_FILA.NU_MATRICULA    
FROM TB_SEL_SENHA_FILA    
LEFT JOIN TB_PAC_TRIAGEM  ON (TB_SEL_SENHA_FILA.PK_SELSEN  = TB_PAC_TRIAGEM.FK_COD_SENHA)    
LEFT JOIN TE_ALERTA_TRIAG ON (TB_PAC_TRIAGEM.FK_ATRIAG_ENF = TE_ALERTA_TRIAG.PK_ATRIAG)   
INNER JOIN TE_STATUS_TRIAG ON (TB_SEL_SENHA_FILA.FK_STRIAG  = TE_STATUS_TRIAG.PK_STRIAG)   
INNER JOIN FAESPCAD ON (TB_SEL_SENHA_FILA.FK_COD_ESP = FAESPCAD.COD_ESP)    
LEFT JOIN FAUSUCAD ON (TB_PAC_TRIAGEM.FK_MATRICULA  = FAUSUCAD.MATRICULA)    
LEFT JOIN FAPACCAD ON (FAPACCAD.COD_PAC = TB_SEL_SENHA_FILA.FK_COD_PAC)    
LEFT JOIN FAPRTCAD ON (FAPACCAD.COD_PRT = FAPRTCAD.COD_PRT)    
LEFT JOIN  TM_CARGA_BENEF ON (TM_CARGA_BENEF.NU_MATRICULA = TB_SEL_SENHA_FILA.NU_MATRICULA)   
WHERE TB_SEL_SENHA_FILA.FK_COD_UNI = '0012' 
AND TB_SEL_SENHA_FILA.DH_RETIRADA  >= TO_DATE('29/09/2014 00:00:00','%d/%m/%Y %H:%M:%S') 
AND TB_SEL_SENHA_FILA.DH_RETIRADA  <= TO_DATE('29/09/2014 23:59:59','%d/%m/%Y %H:%M:%S') 
AND TB_SEL_SENHA_FILA.FK_STRIAG IN (8) 
order by pk_selsen