  SELECT '' || PRESCRICAO_PAC.DATA_HORA_INI AS ORDEM,
         ITEM_DISTRIB.COD_PAC,
         ITEM_DISTRIB.CODIGO,
         ITEM_DISTRIB.COD_SAL,
         ITEM_DISTRIB.DATA_HORA_INI,
         ITEM_DISTRIB.DATA_HORA_PRES,
         LPAD(INTEGERTOCHAR(COD_MAPA),10,0) COD_MAPA,
         ITEM_DISTRIB.QTDE_SOLICITADA,
         ITEM_DISTRIB.QTDE_ATENDIDA,
         ITEM_DISTRIB.COD_SET,
         ITEM_DISTRIB.STATUS_HORARIO,
         ITEM_DISTRIB.SEQ_COD_BARRA,
         ITEM_DISTRIB.STATUS_SEQ,
         PRESCRICAO_PAC.FAMILIA,
         PRESCRICAO_PAC.CODIGO_PAI,
         PRESCRICAO_PAC.TIPO,
         PRESCRICAO_PAC.COD_SAL_PAI,
         TO_CHAR(DATA_ALTA) DATA_ALTA,
         INTERVALTOCHAR(HORA_ALTA) HORA_ALTA,
         NOME_PAC,
         DATA_ALTA_MEDICA,
         FAPACCAD.COD_UNI,
         FAAPTCAD.COD_SET AS COD_SET_PAC,
         FATIPCAD.PRE_CLASS,
         NVL(DECODE(FATIPCAD.PRE_CLASS,'KIT','-'),'S') AS SALDO,
         (SELECT F.TIPO_CONS FROM FAPRDCAD F WHERE F.CODIGO = PRESCRICAO_PAC.CODIGO_PAI) AS TIPO_CONS_PAI,
         NVL('B' || PRESCRICAO_PAC.CODIGO_PAI,NVL('A' || (SELECT DISTINCT A.COD_KIT FROM FAKITPRD A WHERE A.COD_KIT = FAPRDCAD.CODIGO),'0000000')) CODKIT,
         PRESCRICAO_PAC.COD_KIT,
         PRESCRICAO_PAC.COD_VIA
    FROM ITEM_DISTRIB ITEM_DISTRIB JOIN PRESCRICAO_PAC ON (ITEM_DISTRIB.COD_PAC = PRESCRICAO_PAC.COD_PAC) AND (ITEM_DISTRIB.CODIGO = PRESCRICAO_PAC.CODIGO OR ITEM_DISTRIB.COD_SAL = PRESCRICAO_PAC.COD_SAL) AND (ITEM_DISTRIB.DATA_HORA_INI = PRESCRICAO_PAC.DATA_HORA_INI) JOIN FAPACCAD ON ITEM_DISTRIB.COD_PAC = FAPACCAD.COD_PAC JOIN FAPRTCAD ON FAPACCAD.COD_PRT = FAPRTCAD.COD_PRT JOIN FAPRDCAD ON ITEM_DISTRIB.CODIGO = FAPRDCAD.CODIGO JOIN FATIPCAD ON FAPRDCAD.TIPO_PRD = FATIPCAD.TIPO_PRD INNER JOIN FALEICAD ON FAPACCAD.LEITO = FALEICAD.LEITO INNER JOIN FAAPTCAD ON FALEICAD.COD_APT = FAAPTCAD.COD_APT
   WHERE (1 = 1)
         AND (ITEM_DISTRIB.COD_SET_EST_DISP = '3117')
         AND ((PRESCRICAO_PAC.ITEM_VALIDO = 'S') OR (PRESCRICAO_PAC.ITEM_VALIDO = 'N'))
         AND (STATUS_HORARIO <> 'S')
         AND FAPACCAD.TIPO_PAC = 'I'
         AND (PRESCRICAO_PAC.DATA_HORA_INI_PAI IS NULL)
         AND NVL(PRESCRICAO_PAC.SN_USO_PARTICULAR,'N') = 'N'
         AND (DATA_HORA_PRES >= '2012-05-11 08:00:00')
         AND (DATA_HORA_PRES <= '2012-05-11 14:00:00')
         AND (DT_HR_VALIDADE >= '2012-02-11 08:00:00')
         AND (COD_MAPA IS NULL)
         AND (ITEM_DISTRIB.COD_PAC = 'CQ90545')
         AND (NVL(FAPRDCAD.TIPO_CONS,0) = 0)
         AND ((PRESCRICAO_PAC.CODIGO_PAI IS NULL) OR ((SELECT NVL(F.TIPO_CONS,0) FROM FAPRDCAD F WHERE F.CODIGO = PRESCRICAO_PAC.CODIGO_PAI) = 0))
         --AND FAPACCAD.COD_UNI IN ('0003','0002','0032','EGB','LIFE')
 UNION 
  SELECT '' || PRESCRICAO_PAC.DATA_HORA_INI_PAI || PRESCRICAO_PAC.DATA_HORA_INI AS ORDEM,
         ITEM_DISTRIB.COD_PAC,
         ITEM_DISTRIB.CODIGO,
         ITEM_DISTRIB.COD_SAL,
         ITEM_DISTRIB.DATA_HORA_INI,
         ITEM_DISTRIB.DATA_HORA_PRES,
         LPAD(INTEGERTOCHAR(COD_MAPA),10,0) COD_MAPA,
         ITEM_DISTRIB.QTDE_SOLICITADA,
         ITEM_DISTRIB.QTDE_ATENDIDA,
         ITEM_DISTRIB.COD_SET,
         ITEM_DISTRIB.STATUS_HORARIO,
         ITEM_DISTRIB.SEQ_COD_BARRA,
         ITEM_DISTRIB.STATUS_SEQ,
         PRESCRICAO_PAC.FAMILIA,
         PRESCRICAO_PAC.CODIGO_PAI,
         PRESCRICAO_PAC.TIPO,
         PRESCRICAO_PAC.COD_SAL_PAI,
         TO_CHAR(DATA_ALTA) DATA_ALTA,
         INTERVALTOCHAR(HORA_ALTA) HORA_ALTA,
         NOME_PAC,
         DATA_ALTA_MEDICA,
         FAPACCAD.COD_UNI,
         FAAPTCAD.COD_SET AS COD_SET_PAC,
         FATIPCAD.PRE_CLASS,
         NVL(DECODE(FATIPCAD.PRE_CLASS,'KIT','-'),'S') AS SALDO,
         (SELECT F.TIPO_CONS FROM FAPRDCAD F WHERE F.CODIGO = PRESCRICAO_PAC.CODIGO_PAI) AS TIPO_CONS_PAI,
         NVL('B' || PRESCRICAO_PAC.CODIGO_PAI,NVL('A' || (SELECT DISTINCT A.COD_KIT FROM FAKITPRD A WHERE A.COD_KIT = FAPRDCAD.CODIGO),'0000000')) CODKIT,
         PRESCRICAO_PAC.COD_KIT,
         PRESCRICAO_PAC.COD_VIA
    FROM ITEM_DISTRIB ITEM_DISTRIB JOIN PRESCRICAO_PAC ON (ITEM_DISTRIB.COD_PAC = PRESCRICAO_PAC.COD_PAC) AND (ITEM_DISTRIB.CODIGO = PRESCRICAO_PAC.CODIGO OR ITEM_DISTRIB.COD_SAL = PRESCRICAO_PAC.COD_SAL) AND (ITEM_DISTRIB.DATA_HORA_INI = PRESCRICAO_PAC.DATA_HORA_INI) JOIN FAPACCAD ON ITEM_DISTRIB.COD_PAC = FAPACCAD.COD_PAC JOIN FAPRTCAD ON FAPACCAD.COD_PRT = FAPRTCAD.COD_PRT JOIN FAPRDCAD ON ITEM_DISTRIB.CODIGO = FAPRDCAD.CODIGO JOIN FATIPCAD ON FAPRDCAD.TIPO_PRD = FATIPCAD.TIPO_PRD INNER JOIN FALEICAD ON FAPACCAD.LEITO = FALEICAD.LEITO INNER JOIN FAAPTCAD ON FALEICAD.COD_APT = FAAPTCAD.COD_APT
   WHERE (1 = 1)
         AND (ITEM_DISTRIB.COD_SET_EST_DISP = '3117')
         AND (STATUS_HORARIO <> 'S')
         AND FAPACCAD.TIPO_PAC = 'I'
         AND ((PRESCRICAO_PAC.ITEM_VALIDO = 'S') OR (PRESCRICAO_PAC.ITEM_VALIDO = 'N'))
         AND NOT (PRESCRICAO_PAC.DATA_HORA_INI_PAI IS NULL)
         AND NVL(PRESCRICAO_PAC.SN_USO_PARTICULAR,'N') = 'N'
         AND (DATA_HORA_PRES >= '2012-05-11 08:00:00')
         AND (DATA_HORA_PRES <= '2012-05-11 14:00:00')
         AND (DT_HR_VALIDADE >= '2012-02-11 08:00:00')
         AND (COD_MAPA IS NULL)
         AND (ITEM_DISTRIB.COD_PAC = 'CQ90545')
         AND (NVL(FAPRDCAD.TIPO_CONS,0) = 0)
         AND ((PRESCRICAO_PAC.CODIGO_PAI IS NULL) OR ((SELECT NVL(F.TIPO_CONS,0) FROM FAPRDCAD F WHERE F.CODIGO = PRESCRICAO_PAC.CODIGO_PAI) = 0))
         --AND FAPACCAD.COD_UNI IN ('0003','0002','0032','EGB','LIFE')
 UNION 
  SELECT '' || PRESCRICAO_PAC.DATA_HORA_INI AS ORDEM,
         ITEM_DISTRIB.COD_PAC,
         ITEM_DISTRIB.CODIGO,
         ITEM_DISTRIB.COD_SAL,
         ITEM_DISTRIB.DATA_HORA_INI,
         ITEM_DISTRIB.DATA_HORA_PRES,
         LPAD(INTEGERTOCHAR(COD_MAPA),10,0) COD_MAPA,
         ITEM_DISTRIB.QTDE_SOLICITADA,
         ITEM_DISTRIB.QTDE_ATENDIDA,
         ITEM_DISTRIB.COD_SET,
         ITEM_DISTRIB.STATUS_HORARIO,
         ITEM_DISTRIB.SEQ_COD_BARRA,
         ITEM_DISTRIB.STATUS_SEQ,
         PRESCRICAO_PAC.FAMILIA,
         PRESCRICAO_PAC.CODIGO_PAI,
         PRESCRICAO_PAC.TIPO,
         PRESCRICAO_PAC.COD_SAL_PAI,
         TO_CHAR(DATA_ALTA) DATA_ALTA,
         INTERVALTOCHAR(HORA_ALTA) HORA_ALTA,
         NOME_PAC,
         DATA_ALTA_MEDICA,
         FAPACCAD.COD_UNI,
         FAPACCOM.COD_SET AS COD_SET_PAC,
         FATIPCAD.PRE_CLASS,
         NVL(DECODE(FATIPCAD.PRE_CLASS,'KIT','-'),'S') AS SALDO,
         (SELECT F.TIPO_CONS FROM FAPRDCAD F WHERE F.CODIGO = PRESCRICAO_PAC.CODIGO_PAI) AS TIPO_CONS_PAI,
         NVL('B' || PRESCRICAO_PAC.CODIGO_PAI,NVL('A' || (SELECT DISTINCT A.COD_KIT FROM FAKITPRD A WHERE A.COD_KIT = FAPRDCAD.CODIGO),'0000000')) CODKIT,
         PRESCRICAO_PAC.COD_KIT,
         PRESCRICAO_PAC.COD_VIA
    FROM ITEM_DISTRIB ITEM_DISTRIB,
         PRESCRICAO_PAC,
         FAPACCAD,
         FAPRTCAD,
         FAPACCOM,
         FASETCAD,
         FAPRDCAD,
         FATIPCAD
   WHERE (ITEM_DISTRIB.COD_PAC = PRESCRICAO_PAC.COD_PAC)
         AND ((ITEM_DISTRIB.CODIGO = PRESCRICAO_PAC.CODIGO) OR (ITEM_DISTRIB.COD_SAL = PRESCRICAO_PAC.COD_SAL))
         AND (ITEM_DISTRIB.DATA_HORA_INI = PRESCRICAO_PAC.DATA_HORA_INI)
         AND (ITEM_DISTRIB.COD_PAC = FAPACCAD.COD_PAC)
         AND (FAPACCAD.COD_PRT = FAPRTCAD.COD_PRT)
         AND (FAPACCAD.COD_PAC = FAPACCOM.COD_PAC)
         AND (ITEM_DISTRIB.COD_SET = FASETCAD.COD_SET)
         AND (ITEM_DISTRIB.CODIGO = FAPRDCAD.CODIGO)
         AND (FAPRDCAD.TIPO_PRD = FATIPCAD.TIPO_PRD)
         AND (ITEM_DISTRIB.COD_SET_EST_DISP = '3117')
         AND (FAPACCAD.TIPO_PAC <> 'I')
         AND ((PRESCRICAO_PAC.ITEM_VALIDO = 'S') OR (PRESCRICAO_PAC.ITEM_VALIDO = 'N'))
         AND (STATUS_HORARIO <> 'S')
         AND (PRESCRICAO_PAC.DATA_HORA_INI_PAI IS NULL)
         AND NVL(PRESCRICAO_PAC.SN_USO_PARTICULAR,'N') = 'N'
         AND (FAPACCAD.DATA_ALTA IS NULL OR TO_DATE((FAPACCAD.DATA_ALTA ||' ' || FAPACCAD.HORA_ALTA),'%d/%m/%Y %H:%M') > '2012-02-13 08:00:00')
         AND (DATA_HORA_PRES >= '2012-05-11 08:00:00')
         AND (DATA_HORA_PRES <= '2012-05-11 14:00:00')
         AND (DT_HR_VALIDADE >= '2012-02-11 08:00:00')
         AND (COD_MAPA IS NULL)
         AND (ITEM_DISTRIB.COD_PAC = 'CQ90545')
         AND (FAPRDCAD.TIPO_CONS = 0)
         AND ((PRESCRICAO_PAC.CODIGO_PAI IS NULL) OR ((SELECT F.TIPO_CONS FROM FAPRDCAD F WHERE F.CODIGO = PRESCRICAO_PAC.CODIGO_PAI) = 0))
         --AND FAPACCAD.COD_UNI IN ('0003','0002','0032','EGB','LIFE')
 UNION 
  SELECT '' || PRESCRICAO_PAC.DATA_HORA_INI_PAI || PRESCRICAO_PAC.DATA_HORA_INI AS ORDEM,
         ITEM_DISTRIB.COD_PAC,
         ITEM_DISTRIB.CODIGO,
         ITEM_DISTRIB.COD_SAL,
         ITEM_DISTRIB.DATA_HORA_INI,
         ITEM_DISTRIB.DATA_HORA_PRES,
         LPAD(INTEGERTOCHAR(COD_MAPA),10,0) COD_MAPA,
         ITEM_DISTRIB.QTDE_SOLICITADA,
         ITEM_DISTRIB.QTDE_ATENDIDA,
         ITEM_DISTRIB.COD_SET,
         ITEM_DISTRIB.STATUS_HORARIO,
         ITEM_DISTRIB.SEQ_COD_BARRA,
         ITEM_DISTRIB.STATUS_SEQ,
         PRESCRICAO_PAC.FAMILIA,
         PRESCRICAO_PAC.CODIGO_PAI,
         PRESCRICAO_PAC.TIPO,
         PRESCRICAO_PAC.COD_SAL_PAI,
         TO_CHAR(DATA_ALTA) DATA_ALTA,
         INTERVALTOCHAR(HORA_ALTA) HORA_ALTA,
         NOME_PAC,
         DATA_ALTA_MEDICA,
         FAPACCAD.COD_UNI,
         FAPACCOM.COD_SET AS COD_SET_PAC,
         FATIPCAD.PRE_CLASS,
         NVL(DECODE(FATIPCAD.PRE_CLASS,'KIT','-'),'S') AS SALDO,
         (SELECT F.TIPO_CONS FROM FAPRDCAD F WHERE F.CODIGO = PRESCRICAO_PAC.CODIGO_PAI) AS TIPO_CONS_PAI,
         NVL('B' || PRESCRICAO_PAC.CODIGO_PAI,NVL('A' || (SELECT DISTINCT A.COD_KIT FROM FAKITPRD A WHERE A.COD_KIT = FAPRDCAD.CODIGO),'0000000')) CODKIT,
         PRESCRICAO_PAC.COD_KIT,
         PRESCRICAO_PAC.COD_VIA
    FROM ITEM_DISTRIB ITEM_DISTRIB,
         PRESCRICAO_PAC,
         FAPACCAD,
         FAPRTCAD,
         FAPACCOM,
         FASETCAD,
         FAPRDCAD,
         FATIPCAD
   WHERE ITEM_DISTRIB.COD_PAC = PRESCRICAO_PAC.COD_PAC
         AND ((ITEM_DISTRIB.CODIGO = PRESCRICAO_PAC.CODIGO) OR (ITEM_DISTRIB.COD_SAL = PRESCRICAO_PAC.COD_SAL))
         AND (ITEM_DISTRIB.DATA_HORA_INI = PRESCRICAO_PAC.DATA_HORA_INI)
         AND (ITEM_DISTRIB.COD_PAC = FAPACCAD.COD_PAC)
         AND (FAPACCAD.COD_PRT = FAPRTCAD.COD_PRT)
         AND (FAPACCAD.COD_PAC = FAPACCOM.COD_PAC)
         AND (ITEM_DISTRIB.COD_SET = FASETCAD.COD_SET)
         AND (ITEM_DISTRIB.CODIGO = FAPRDCAD.CODIGO)
         AND (FAPRDCAD.TIPO_PRD = FATIPCAD.TIPO_PRD)
         AND (ITEM_DISTRIB.COD_SET_EST_DISP = '3117')
         AND (FAPACCAD.TIPO_PAC <> 'I')
         AND ((PRESCRICAO_PAC.ITEM_VALIDO = 'S') OR (PRESCRICAO_PAC.ITEM_VALIDO = 'N'))
         AND (STATUS_HORARIO <> 'S')
         AND NOT (PRESCRICAO_PAC.DATA_HORA_INI_PAI IS NULL)
         AND NVL(PRESCRICAO_PAC.SN_USO_PARTICULAR,'N') = 'N'
         AND NOT (PRESCRICAO_PAC.DATA_HORA_INI_PAI IS NULL)
         AND ((FAPACCAD.DATA_ALTA IS NULL OR TO_DATE((FAPACCAD.DATA_ALTA ||' ' || FAPACCAD.HORA_ALTA),'%d/%m/%Y %H:%M') > '2012-02-13 08:00:00'))
         AND (DATA_HORA_PRES >= '2012-05-11 08:00:00')
         AND (DATA_HORA_PRES <= '2012-05-11 14:00:00')
         AND (DT_HR_VALIDADE >= '2012-02-11 08:00:00')
         AND (COD_MAPA IS NULL)
         AND (ITEM_DISTRIB.COD_PAC = 'CQ90545')
         AND (FAPRDCAD.TIPO_CONS = 0)
         AND ((PRESCRICAO_PAC.CODIGO_PAI IS NULL) OR ((SELECT F.TIPO_CONS FROM FAPRDCAD F WHERE F.CODIGO = PRESCRICAO_PAC.CODIGO_PAI) = 0))
         --AND FAPACCAD.COD_UNI IN ('0003','0002','0032','EGB','LIFE')
ORDER BY 6, 1, 27



modificado para contemplar o e-mail enviado pelo nivaldo
select * from prescricao_pac where cod_pac in ('CQ90545') and codigo in('000403')
select * from item_distrib where cod_pac in ('CQ90545') and status_horario = 'D' and codigo = '000403'
consumo 3203
estoque 3117

  SELECT '' || PRESCRICAO_PAC.DATA_HORA_INI AS ORDEM,
         ITEM_DISTRIB.COD_PAC,
         ITEM_DISTRIB.CODIGO,
         ITEM_DISTRIB.COD_SAL,
         ITEM_DISTRIB.DATA_HORA_INI,
         ITEM_DISTRIB.DATA_HORA_PRES,
         LPAD(INTEGERTOCHAR(COD_MAPA),10,0) COD_MAPA,
         ITEM_DISTRIB.QTDE_SOLICITADA,
         ITEM_DISTRIB.QTDE_ATENDIDA,
         ITEM_DISTRIB.COD_SET,
         ITEM_DISTRIB.STATUS_HORARIO,
         ITEM_DISTRIB.SEQ_COD_BARRA,
         ITEM_DISTRIB.STATUS_SEQ,
         PRESCRICAO_PAC.FAMILIA,
         PRESCRICAO_PAC.CODIGO_PAI,
         PRESCRICAO_PAC.TIPO,
         PRESCRICAO_PAC.COD_SAL_PAI,
         TO_CHAR(DATA_ALTA) DATA_ALTA,
         INTERVALTOCHAR(HORA_ALTA) HORA_ALTA,
         NOME_PAC,
         DATA_ALTA_MEDICA,
         FAPACCAD.COD_UNI,
         --FAAPTCAD.COD_SET AS COD_SET_PAC,
         FATIPCAD.PRE_CLASS,
         NVL(DECODE(FATIPCAD.PRE_CLASS,'KIT','-'),'S') AS SALDO,
         (SELECT F.TIPO_CONS FROM FAPRDCAD F WHERE F.CODIGO = PRESCRICAO_PAC.CODIGO_PAI) AS TIPO_CONS_PAI,
         NVL('B' || PRESCRICAO_PAC.CODIGO_PAI,NVL('A' || (SELECT DISTINCT A.COD_KIT FROM FAKITPRD A WHERE A.COD_KIT = FAPRDCAD.CODIGO),'0000000')) CODKIT,
         PRESCRICAO_PAC.COD_KIT,
         PRESCRICAO_PAC.COD_VIA
    FROM ITEM_DISTRIB ITEM_DISTRIB JOIN PRESCRICAO_PAC ON (ITEM_DISTRIB.COD_PAC = PRESCRICAO_PAC.COD_PAC) AND (ITEM_DISTRIB.CODIGO = PRESCRICAO_PAC.CODIGO OR ITEM_DISTRIB.COD_SAL = PRESCRICAO_PAC.COD_SAL) AND (ITEM_DISTRIB.DATA_HORA_INI = PRESCRICAO_PAC.DATA_HORA_INI) JOIN FAPACCAD ON ITEM_DISTRIB.COD_PAC = FAPACCAD.COD_PAC JOIN FAPRTCAD ON FAPACCAD.COD_PRT = FAPRTCAD.COD_PRT JOIN FAPRDCAD ON ITEM_DISTRIB.CODIGO = FAPRDCAD.CODIGO JOIN FATIPCAD ON FAPRDCAD.TIPO_PRD = FATIPCAD.TIPO_PRD --INNER JOIN FALEICAD ON FAPACCAD.LEITO = FALEICAD.LEITO INNER JOIN FAAPTCAD ON FALEICAD.COD_APT = FAAPTCAD.COD_APT
   WHERE (1 = 1)
         AND (ITEM_DISTRIB.COD_SET_EST_DISP = '3117')
         AND ((PRESCRICAO_PAC.ITEM_VALIDO = 'S') OR (PRESCRICAO_PAC.ITEM_VALIDO = 'N'))
         AND (STATUS_HORARIO <> 'S')
         AND FAPACCAD.TIPO_PAC = 'I'
         AND (PRESCRICAO_PAC.DATA_HORA_INI_PAI IS NULL)
         AND NVL(PRESCRICAO_PAC.SN_USO_PARTICULAR,'N') = 'N'
         AND (DATA_HORA_PRES >= '2012-05-11 12:00:00')
         AND (DATA_HORA_PRES <= '2012-05-11 14:00:00')
         AND (DT_HR_VALIDADE >= '2012-05-11 12:00:00')
         AND (COD_MAPA IS NULL)
         AND (ITEM_DISTRIB.COD_PAC = 'CQ90545')
         AND (NVL(FAPRDCAD.TIPO_CONS,0) = 0)
         AND ((PRESCRICAO_PAC.CODIGO_PAI IS NULL) OR ((SELECT NVL(F.TIPO_CONS,0) FROM FAPRDCAD F WHERE F.CODIGO = PRESCRICAO_PAC.CODIGO_PAI) = 0))
         --AND FAPACCAD.COD_UNI IN ('0003','0002','0032','EGB','LIFE')
 UNION 
  SELECT '' || PRESCRICAO_PAC.DATA_HORA_INI_PAI || PRESCRICAO_PAC.DATA_HORA_INI AS ORDEM,
         ITEM_DISTRIB.COD_PAC,
         ITEM_DISTRIB.CODIGO,
         ITEM_DISTRIB.COD_SAL,
         ITEM_DISTRIB.DATA_HORA_INI,
         ITEM_DISTRIB.DATA_HORA_PRES,
         LPAD(INTEGERTOCHAR(COD_MAPA),10,0) COD_MAPA,
         ITEM_DISTRIB.QTDE_SOLICITADA,
         ITEM_DISTRIB.QTDE_ATENDIDA,
         ITEM_DISTRIB.COD_SET,
         ITEM_DISTRIB.STATUS_HORARIO,
         ITEM_DISTRIB.SEQ_COD_BARRA,
         ITEM_DISTRIB.STATUS_SEQ,
         PRESCRICAO_PAC.FAMILIA,
         PRESCRICAO_PAC.CODIGO_PAI,
         PRESCRICAO_PAC.TIPO,
         PRESCRICAO_PAC.COD_SAL_PAI,
         TO_CHAR(DATA_ALTA) DATA_ALTA,
         INTERVALTOCHAR(HORA_ALTA) HORA_ALTA,
         NOME_PAC,
         DATA_ALTA_MEDICA,
         FAPACCAD.COD_UNI,
        -- FAAPTCAD.COD_SET AS COD_SET_PAC,
         FATIPCAD.PRE_CLASS,
         NVL(DECODE(FATIPCAD.PRE_CLASS,'KIT','-'),'S') AS SALDO,
         (SELECT F.TIPO_CONS FROM FAPRDCAD F WHERE F.CODIGO = PRESCRICAO_PAC.CODIGO_PAI) AS TIPO_CONS_PAI,
         NVL('B' || PRESCRICAO_PAC.CODIGO_PAI,NVL('A' || (SELECT DISTINCT A.COD_KIT FROM FAKITPRD A WHERE A.COD_KIT = FAPRDCAD.CODIGO),'0000000')) CODKIT,
         PRESCRICAO_PAC.COD_KIT,
         PRESCRICAO_PAC.COD_VIA
    FROM ITEM_DISTRIB ITEM_DISTRIB JOIN PRESCRICAO_PAC ON (ITEM_DISTRIB.COD_PAC = PRESCRICAO_PAC.COD_PAC) AND (ITEM_DISTRIB.CODIGO = PRESCRICAO_PAC.CODIGO OR ITEM_DISTRIB.COD_SAL = PRESCRICAO_PAC.COD_SAL) AND (ITEM_DISTRIB.DATA_HORA_INI = PRESCRICAO_PAC.DATA_HORA_INI) JOIN FAPACCAD ON ITEM_DISTRIB.COD_PAC = FAPACCAD.COD_PAC JOIN FAPRTCAD ON FAPACCAD.COD_PRT = FAPRTCAD.COD_PRT JOIN FAPRDCAD ON ITEM_DISTRIB.CODIGO = FAPRDCAD.CODIGO JOIN FATIPCAD ON FAPRDCAD.TIPO_PRD = FATIPCAD.TIPO_PRD --INNER JOIN FALEICAD ON FAPACCAD.LEITO = FALEICAD.LEITO INNER JOIN FAAPTCAD ON FALEICAD.COD_APT = FAAPTCAD.COD_APT
   WHERE (1 = 1)
         AND (ITEM_DISTRIB.COD_SET_EST_DISP = '3117')
         AND (STATUS_HORARIO <> 'S')
         AND FAPACCAD.TIPO_PAC = 'I'
         AND ((PRESCRICAO_PAC.ITEM_VALIDO = 'S') OR (PRESCRICAO_PAC.ITEM_VALIDO = 'N'))
         AND NOT (PRESCRICAO_PAC.DATA_HORA_INI_PAI IS NULL)
         AND NVL(PRESCRICAO_PAC.SN_USO_PARTICULAR,'N') = 'N'
         AND (DATA_HORA_PRES >= '2012-05-11 12:00:00')
         AND (DATA_HORA_PRES <= '2012-05-11 14:00:00')
         AND (DT_HR_VALIDADE >= '2012-05-11 12:00:00')
         AND (COD_MAPA IS NULL)
         AND (ITEM_DISTRIB.COD_PAC = 'CQ90545')
         AND (NVL(FAPRDCAD.TIPO_CONS,0) = 0)
         AND ((PRESCRICAO_PAC.CODIGO_PAI IS NULL) OR ((SELECT NVL(F.TIPO_CONS,0) FROM FAPRDCAD F WHERE F.CODIGO = PRESCRICAO_PAC.CODIGO_PAI) = 0))
         --AND FAPACCAD.COD_UNI IN ('0003','0002','0032','EGB','LIFE')
 UNION 
  SELECT '' || PRESCRICAO_PAC.DATA_HORA_INI AS ORDEM,
         ITEM_DISTRIB.COD_PAC,
         ITEM_DISTRIB.CODIGO,
         ITEM_DISTRIB.COD_SAL,
         ITEM_DISTRIB.DATA_HORA_INI,
         ITEM_DISTRIB.DATA_HORA_PRES,
         LPAD(INTEGERTOCHAR(COD_MAPA),10,0) COD_MAPA,
         ITEM_DISTRIB.QTDE_SOLICITADA,
         ITEM_DISTRIB.QTDE_ATENDIDA,
         ITEM_DISTRIB.COD_SET,
         ITEM_DISTRIB.STATUS_HORARIO,
         ITEM_DISTRIB.SEQ_COD_BARRA,
         ITEM_DISTRIB.STATUS_SEQ,
         PRESCRICAO_PAC.FAMILIA,
         PRESCRICAO_PAC.CODIGO_PAI,
         PRESCRICAO_PAC.TIPO,
         PRESCRICAO_PAC.COD_SAL_PAI,
         TO_CHAR(DATA_ALTA) DATA_ALTA,
         INTERVALTOCHAR(HORA_ALTA) HORA_ALTA,
         NOME_PAC,
         DATA_ALTA_MEDICA,
         FAPACCAD.COD_UNI,
         --FAPACCOM.COD_SET AS COD_SET_PAC,
         FATIPCAD.PRE_CLASS,
         NVL(DECODE(FATIPCAD.PRE_CLASS,'KIT','-'),'S') AS SALDO,
         (SELECT F.TIPO_CONS FROM FAPRDCAD F WHERE F.CODIGO = PRESCRICAO_PAC.CODIGO_PAI) AS TIPO_CONS_PAI,
         NVL('B' || PRESCRICAO_PAC.CODIGO_PAI,NVL('A' || (SELECT DISTINCT A.COD_KIT FROM FAKITPRD A WHERE A.COD_KIT = FAPRDCAD.CODIGO),'0000000')) CODKIT,
         PRESCRICAO_PAC.COD_KIT,
         PRESCRICAO_PAC.COD_VIA
    FROM ITEM_DISTRIB ITEM_DISTRIB,
         PRESCRICAO_PAC,
         FAPACCAD,
         FAPRTCAD,
         FAPACCOM,
         FASETCAD,
         FAPRDCAD,
         FATIPCAD
   WHERE (ITEM_DISTRIB.COD_PAC = PRESCRICAO_PAC.COD_PAC)
         AND ((ITEM_DISTRIB.CODIGO = PRESCRICAO_PAC.CODIGO) OR (ITEM_DISTRIB.COD_SAL = PRESCRICAO_PAC.COD_SAL))
         AND (ITEM_DISTRIB.DATA_HORA_INI = PRESCRICAO_PAC.DATA_HORA_INI)
         AND (ITEM_DISTRIB.COD_PAC = FAPACCAD.COD_PAC)
         AND (FAPACCAD.COD_PRT = FAPRTCAD.COD_PRT)
         AND (FAPACCAD.COD_PAC = FAPACCOM.COD_PAC)
         AND (ITEM_DISTRIB.COD_SET = FASETCAD.COD_SET)
         AND (ITEM_DISTRIB.CODIGO = FAPRDCAD.CODIGO)
         AND (FAPRDCAD.TIPO_PRD = FATIPCAD.TIPO_PRD)
         AND (ITEM_DISTRIB.COD_SET_EST_DISP = '3117')
         AND (FAPACCAD.TIPO_PAC <> 'I')
         AND ((PRESCRICAO_PAC.ITEM_VALIDO = 'S') OR (PRESCRICAO_PAC.ITEM_VALIDO = 'N'))
         AND (STATUS_HORARIO <> 'S')
         AND (PRESCRICAO_PAC.DATA_HORA_INI_PAI IS NULL)
         AND NVL(PRESCRICAO_PAC.SN_USO_PARTICULAR,'N') = 'N'
         AND (FAPACCAD.DATA_ALTA IS NULL OR TO_DATE((FAPACCAD.DATA_ALTA ||' ' || FAPACCAD.HORA_ALTA),'%d/%m/%Y %H:%M') > '2012-02-13 08:00:00')
         AND (DATA_HORA_PRES >= '2012-05-11 12:00:00')
         AND (DATA_HORA_PRES <= '2012-05-11 14:00:00')
         AND (DT_HR_VALIDADE >= '2012-05-11 12:00:00')
         AND (COD_MAPA IS NULL)
         AND (ITEM_DISTRIB.COD_PAC = 'CQ90545')
         AND (FAPRDCAD.TIPO_CONS = 0)
         AND ((PRESCRICAO_PAC.CODIGO_PAI IS NULL) OR ((SELECT F.TIPO_CONS FROM FAPRDCAD F WHERE F.CODIGO = PRESCRICAO_PAC.CODIGO_PAI) = 0))
         --AND FAPACCAD.COD_UNI IN ('0003','0002','0032','EGB','LIFE')
 UNION 
  SELECT '' || PRESCRICAO_PAC.DATA_HORA_INI_PAI || PRESCRICAO_PAC.DATA_HORA_INI AS ORDEM,
         ITEM_DISTRIB.COD_PAC,
         ITEM_DISTRIB.CODIGO,
         ITEM_DISTRIB.COD_SAL,
         ITEM_DISTRIB.DATA_HORA_INI,
         ITEM_DISTRIB.DATA_HORA_PRES,
         LPAD(INTEGERTOCHAR(COD_MAPA),10,0) COD_MAPA,
         ITEM_DISTRIB.QTDE_SOLICITADA,
         ITEM_DISTRIB.QTDE_ATENDIDA,
         ITEM_DISTRIB.COD_SET,
         ITEM_DISTRIB.STATUS_HORARIO,
         ITEM_DISTRIB.SEQ_COD_BARRA,
         ITEM_DISTRIB.STATUS_SEQ,
         PRESCRICAO_PAC.FAMILIA,
         PRESCRICAO_PAC.CODIGO_PAI,
         PRESCRICAO_PAC.TIPO,
         PRESCRICAO_PAC.COD_SAL_PAI,
         TO_CHAR(DATA_ALTA) DATA_ALTA,
         INTERVALTOCHAR(HORA_ALTA) HORA_ALTA,
         NOME_PAC,
         DATA_ALTA_MEDICA,
         FAPACCAD.COD_UNI,
         --FAPACCOM.COD_SET AS COD_SET_PAC,
         FATIPCAD.PRE_CLASS,
         NVL(DECODE(FATIPCAD.PRE_CLASS,'KIT','-'),'S') AS SALDO,
         (SELECT F.TIPO_CONS FROM FAPRDCAD F WHERE F.CODIGO = PRESCRICAO_PAC.CODIGO_PAI) AS TIPO_CONS_PAI,
         NVL('B' || PRESCRICAO_PAC.CODIGO_PAI,NVL('A' || (SELECT DISTINCT A.COD_KIT FROM FAKITPRD A WHERE A.COD_KIT = FAPRDCAD.CODIGO),'0000000')) CODKIT,
         PRESCRICAO_PAC.COD_KIT,
         PRESCRICAO_PAC.COD_VIA
    FROM ITEM_DISTRIB ITEM_DISTRIB,
         PRESCRICAO_PAC,
         FAPACCAD,
         FAPRTCAD,
         FAPACCOM,
         FASETCAD,
         FAPRDCAD,
         FATIPCAD
   WHERE ITEM_DISTRIB.COD_PAC = PRESCRICAO_PAC.COD_PAC
         AND ((ITEM_DISTRIB.CODIGO = PRESCRICAO_PAC.CODIGO) OR (ITEM_DISTRIB.COD_SAL = PRESCRICAO_PAC.COD_SAL))
         AND (ITEM_DISTRIB.DATA_HORA_INI = PRESCRICAO_PAC.DATA_HORA_INI)
         AND (ITEM_DISTRIB.COD_PAC = FAPACCAD.COD_PAC)
         AND (FAPACCAD.COD_PRT = FAPRTCAD.COD_PRT)
         AND (FAPACCAD.COD_PAC = FAPACCOM.COD_PAC)
         AND (ITEM_DISTRIB.COD_SET = FASETCAD.COD_SET)
         AND (ITEM_DISTRIB.CODIGO = FAPRDCAD.CODIGO)
         AND (FAPRDCAD.TIPO_PRD = FATIPCAD.TIPO_PRD)
         AND (ITEM_DISTRIB.COD_SET_EST_DISP = '3117')
         AND (FAPACCAD.TIPO_PAC <> 'I')
         AND ((PRESCRICAO_PAC.ITEM_VALIDO = 'S') OR (PRESCRICAO_PAC.ITEM_VALIDO = 'N'))
         AND (STATUS_HORARIO <> 'S')
         AND NOT (PRESCRICAO_PAC.DATA_HORA_INI_PAI IS NULL)
         AND NVL(PRESCRICAO_PAC.SN_USO_PARTICULAR,'N') = 'N'
         AND NOT (PRESCRICAO_PAC.DATA_HORA_INI_PAI IS NULL)
         AND ((FAPACCAD.DATA_ALTA IS NULL OR TO_DATE((FAPACCAD.DATA_ALTA ||' ' || FAPACCAD.HORA_ALTA),'%d/%m/%Y %H:%M') > '2012-02-13 08:00:00'))
         AND (DATA_HORA_PRES >= '2012-05-11 12:00:00')
         AND (DATA_HORA_PRES <= '2012-05-11 14:00:00')
         AND (DT_HR_VALIDADE >= '2012-05-11 12:00:00')
         AND (COD_MAPA IS NULL)
         AND (ITEM_DISTRIB.COD_PAC = 'CQ90545')
         AND (FAPRDCAD.TIPO_CONS = 0)
         AND ((PRESCRICAO_PAC.CODIGO_PAI IS NULL) OR ((SELECT F.TIPO_CONS FROM FAPRDCAD F WHERE F.CODIGO = PRESCRICAO_PAC.CODIGO_PAI) = 0))
         --AND FAPACCAD.COD_UNI IN ('0003','0002','0032','EGB','LIFE')
ORDER BY 2, 1, 27