
DECLARE 
    VORDEM VARCHAR2(255):= '0';
    VCOUNT NUMBER:=0;
BEGIN 
    FOR I IN (SELECT O.CO_ORDEM_SAP ORDEM, N.PK_NRMAPROP CODIGO
             FROM SAP.TB_ORDEM_INTERNA O
             INNER JOIN SAP.TB_NORMA_APROPRIACAO N ON O.PK_ORDINT = N.FK_ORDINT
             INNER JOIN SAP.TB_CONTROLE_PROCESSAMENTO P ON P.FK_TP_INTEGRA = 13 AND P.FK_CODIGO = N.PK_NRMAPROP
             WHERE O.CO_ORDEM_SAP IN ('H00002692946','H00002697715') ORDER BY O.CO_ORDEM_SAP, P.DH_PROCESSAMENTO DESC) 
    LOOP
        IF I.ORDEM <> VORDEM THEN 
            VORDEM :=I.ORDEM;
            VCOUNT := VCOUNT + 1;
           -- UPDATE SAP.TB_CONTROLE_PROCESSAMENTO
           -- SET STATUS = 'P' 
           -- WHERE FK_TP_INTEGRA = 13 AND FK_CODIGO = I.CODIGO;
           -- COMMIT;
        ELSE
            CONTINUE;
        END IF;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE(VCOUNT || ' LINHAS ATUALIZADAS.');
END;