-------------------------------------------------------------
-- Inclusão de Mapa - ORCL
-------------------------------------------------------------
--Assunto...: Inclsuão de novos setores de atendimento para o Mapa
--Banco.....: Oracle
--Analista..: Audrey Akemi / Ricardo Aguirra 
--Validado..:
--Data......: 06/2020
--Finalidade: Devido a criação de novos setores de atendimento na unidade houve a necessidade de realizar o atendimento por mapa
--			  assim, para a inclisão dos novos horarios se faz necessario a correção da Sequencia existente para depois a inclusão dos 
--			  novos horarios para atendimento.			  
-------------------------------------------------------------
-- Inclusão de Mapa - ORCL
-------------------------------------------------------------
ALTER SESSION SET current_schema = SISHOSP
/
DECLARE 
	n		NUMBER;
	naux	NUMBER;
BEGIN 
  
  SELECT max(m.pk_setmap) 
  INTO n
  FROM tb_config_setmapa m;
  
  SELECT "SISHOSP"."ISEQ$$_100119".nextval 
  INTO naux
  FROM dual;
  
  n := n-naux;
 
  WHILE n > 0 
  LOOP   
    SELECT "SISHOSP"."ISEQ$$_100119".nextval INTO naux FROM dual;
    n := n-1;
  END LOOP;  
  
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (48,'0067','0334','N','N');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (1,'0067','0334','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (2,'0067','0334','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (3,'0067','0334','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (4,'0067','0334','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (5,'0067','0334','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (6,'0067','0334','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (7,'0067','0334','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (8,'0067','0334','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (9,'0067','0334','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (10,'0067','0334','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (11,'0067','0334','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (12,'0067','0334','N','N');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (13,'0067','0334','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (14,'0067','0334','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (15,'0067','0334','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (16,'0067','0334','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (17,'0067','0334','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (18,'0067','0334','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (19,'0067','0334','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (20,'0067','0334','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (21,'0067','0334','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (22,'0067','0334','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (23,'0067','0334','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (24,'0067','0334','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (25,'0067','0334','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (26,'0067','0334','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (27,'0067','0334','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (28,'0067','0334','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (29,'0067','0334','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (30,'0067','0334','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (31,'0067','0334','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (32,'0067','0334','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (33,'0067','0334','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (34,'0067','0334','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (35,'0067','0334','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (36,'0067','0334','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (37,'0067','0334','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (38,'0067','0334','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (39,'0067','0334','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (40,'0067','0334','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (41,'0067','0334','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (42,'0067','0334','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (43,'0067','0334','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (44,'0067','0334','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (45,'0067','0334','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (46,'0067','0334','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (47,'0067','0334','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (48,'0067','0335','N','N');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (1,'0067','0335','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (2,'0067','0335','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (3,'0067','0335','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (4,'0067','0335','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (5,'0067','0335','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (6,'0067','0335','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (7,'0067','0335','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (8,'0067','0335','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (9,'0067','0335','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (10,'0067','0335','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (11,'0067','0335','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (12,'0067','0335','N','N');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (13,'0067','0335','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (14,'0067','0335','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (15,'0067','0335','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (16,'0067','0335','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (17,'0067','0335','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (18,'0067','0335','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (19,'0067','0335','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (20,'0067','0335','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (21,'0067','0335','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (22,'0067','0335','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (23,'0067','0335','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (24,'0067','0335','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (25,'0067','0335','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (26,'0067','0335','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (27,'0067','0335','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (28,'0067','0335','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (29,'0067','0335','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (30,'0067','0335','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (31,'0067','0335','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (32,'0067','0335','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (33,'0067','0335','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (34,'0067','0335','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (35,'0067','0335','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (36,'0067','0335','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (37,'0067','0335','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (38,'0067','0335','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (39,'0067','0335','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (40,'0067','0335','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (41,'0067','0335','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (42,'0067','0335','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (43,'0067','0335','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (44,'0067','0335','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (45,'0067','0335','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (46,'0067','0335','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (47,'0067','0335','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (48,'0067','0342','N','N');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (1,'0067','0342','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (2,'0067','0342','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (3,'0067','0342','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (4,'0067','0342','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (5,'0067','0342','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (6,'0067','0342','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (7,'0067','0342','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (8,'0067','0342','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (9,'0067','0342','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (10,'0067','0342','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (11,'0067','0342','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (12,'0067','0342','N','N');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (13,'0067','0342','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (14,'0067','0342','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (15,'0067','0342','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (16,'0067','0342','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (17,'0067','0342','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (18,'0067','0342','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (19,'0067','0342','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (20,'0067','0342','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (21,'0067','0342','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (22,'0067','0342','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (23,'0067','0342','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (24,'0067','0342','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (25,'0067','0342','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (26,'0067','0342','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (27,'0067','0342','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (28,'0067','0342','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (29,'0067','0342','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (30,'0067','0342','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (31,'0067','0342','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (32,'0067','0342','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (33,'0067','0342','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (34,'0067','0342','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (35,'0067','0342','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (36,'0067','0342','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (37,'0067','0342','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (38,'0067','0342','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (39,'0067','0342','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (40,'0067','0342','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (41,'0067','0342','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (42,'0067','0342','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (43,'0067','0342','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (44,'0067','0342','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (45,'0067','0342','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (46,'0067','0342','N','S');
	INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
			VALUES (47,'0067','0342','N','S');
	
 COMMIT; 
END;
/

