-------------------------------------------------------------
-- Inclusão de Mapa - ORCL
-------------------------------------------------------------
--Assunto...: Inclsuão de novos setores de atendimento para o Mapa
--Banco.....: Oracle
--Analista..: Audrey Akemi / Ricardo Aguirra 
--Validado..:
--Data......: 06/2020
--Finalidade: Devido a criação de novos setores de atendimento na unidade houve a necessidade de realizar o atendimento por mapa
--			  assim, para a inclisão dos novos horarios se faz necessario a correção da Sequencia existente para depois a inclusão dos 
--			  novos horarios para atendimento.			  
-------------------------------------------------------------
-- Inclusão de Mapa - ORCL
-------------------------------------------------------------
ALTER SESSION SET current_schema = SISHOSP
/
DECLARE 
	n		NUMBER;
	naux	NUMBER;
	vCOUNT	NUMBER;
BEGIN 
  
  SELECT max(m.pk_setmap) 
  INTO n
  FROM tb_config_setmapa m;
  
  SELECT "SISHOSP"."ISEQ$$_100119".nextval 
  INTO naux
  FROM dual;
  
  n := n-naux;
 
  WHILE n > 0 
  LOOP   
    SELECT "SISHOSP"."ISEQ$$_100119".nextval INTO naux FROM dual;
    n := n-1;
  END LOOP;
  
  SELECT COUNT(FUK_CONFMP) 
  INTO vCOUNT 
  FROM TB_CONFIG_SETMAPA 
  WHERE FUK_CONFMP = '1' 
  AND FUK_CO_SETOR_CON = '0334';	
  
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (1,'0067','0334','N','S');	
	END IF;
	
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '2' 
	AND FUK_CO_SETOR_CON = '0334';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (2,'0067','0334','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '3' 
	AND FUK_CO_SETOR_CON = '0334';	
	
	IF vCOUNT = 0 THEN 		
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (3,'0067','0334','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '4' 
	AND FUK_CO_SETOR_CON = '0334';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (4,'0067','0334','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '5' 
	AND FUK_CO_SETOR_CON = '0334';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (5,'0067','0334','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '6' 
	AND FUK_CO_SETOR_CON = '0334';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES(6,'0067','0334','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '7' 
	AND FUK_CO_SETOR_CON = '0334';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (7,'0067','0334','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '8'
	AND FUK_CO_SETOR_CON = '0334';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (8,'0067','0334','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '9' 
	AND FUK_CO_SETOR_CON = '0334';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (9,'0067','0334','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '10' 
	AND FUK_CO_SETOR_CON = '0334';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (10,'0067','0334','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '11' 
	AND FUK_CO_SETOR_CON = '0334';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (11,'0067','0334','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '12' 
	AND FUK_CO_SETOR_CON = '0334';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (12,'0067','0334','N','N');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '13' 
	AND FUK_CO_SETOR_CON = '0334';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (13,'0067','0334','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '14' 
	AND FUK_CO_SETOR_CON = '0334';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (14,'0067','0334','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '15' 
	AND FUK_CO_SETOR_CON = '0334';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (15,'0067','0334','N','S');
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '16' 
	AND FUK_CO_SETOR_CON = '0334';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (16,'0067','0334','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '17' 
	AND FUK_CO_SETOR_CON = '0334';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (17,'0067','0334','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '18'
	AND FUK_CO_SETOR_CON = '0334';

	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (18,'0067','0334','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '19'
	AND FUK_CO_SETOR_CON = '0334';
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (19,'0067','0334','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '20'
	AND FUK_CO_SETOR_CON = '0334';

	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (20,'0067','0334','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '21' 
	AND FUK_CO_SETOR_CON = '0334';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (21,'0067','0334','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '22'
	AND FUK_CO_SETOR_CON = '0334';

	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (22,'0067','0334','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '23'
	AND FUK_CO_SETOR_CON = '0334';

	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (23,'0067','0334','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '24' 
	AND FUK_CO_SETOR_CON = '0334';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (24,'0067','0334','N','N');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '25' 
	AND FUK_CO_SETOR_CON = '0334';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (25,'0067','0334','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '26'
	AND FUK_CO_SETOR_CON = '0334';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (26,'0067','0334','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '27'
	AND FUK_CO_SETOR_CON = '0334';

	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (27,'0067','0334','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '28' 
	AND FUK_CO_SETOR_CON = '0334';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (28,'0067','0334','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '29' 
	AND FUK_CO_SETOR_CON = '0334';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (29,'0067','0334','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '30'
	AND FUK_CO_SETOR_CON = '0334';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (30,'0067','0334','N','N');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '31' 
	AND FUK_CO_SETOR_CON = '0334';

	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (31,'0067','0334','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '32' 
	AND FUK_CO_SETOR_CON = '0334';

	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (32,'0067','0334','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '33'
	AND FUK_CO_SETOR_CON = '0334';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (33,'0067','0334','N','S');	
		END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '34'
	AND FUK_CO_SETOR_CON = '0334';

	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (34,'0067','0334','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '35' 
	AND FUK_CO_SETOR_CON = '0334';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (35,'0067','0334','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '36'
	AND FUK_CO_SETOR_CON = '0334';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (36,'0067','0334','N','N');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '37'
	AND FUK_CO_SETOR_CON = '0334';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (37,'0067','0334','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '38'
	AND FUK_CO_SETOR_CON = '0334';

	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (38,'0067','0334','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '39' 
	AND FUK_CO_SETOR_CON = '0334';

	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (39,'0067','0334','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '40' 
	AND FUK_CO_SETOR_CON = '0334';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (40,'0067','0334','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '41'
	AND FUK_CO_SETOR_CON = '0334';

	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (41,'0067','0334','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '42'
	AND FUK_CO_SETOR_CON = '0334';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (42,'0067','0334','N','N');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '43' 
	AND FUK_CO_SETOR_CON = '0334';

	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (43,'0067','0334','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '44'
	AND FUK_CO_SETOR_CON = '0334';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (44,'0067','0334','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '45'
	AND FUK_CO_SETOR_CON = '0334';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (45,'0067','0334','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '46'
	AND FUK_CO_SETOR_CON = '0334';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (46,'0067','0334','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '47'
	AND FUK_CO_SETOR_CON = '0334';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (47,'0067','0334','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '48'
	AND FUK_CO_SETOR_CON = '0334';

	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (48,'0067','0334','N','N');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '1'
	AND FUK_CO_SETOR_CON = '0335';

	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (1,'0067','0335','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '2' 
	AND FUK_CO_SETOR_CON = '0335';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (2,'0067','0335','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '3' 
	AND FUK_CO_SETOR_CON = '0335';
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (3,'0067','0335','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '4' 
	AND FUK_CO_SETOR_CON = '0335';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (4,'0067','0335','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '5'
	AND FUK_CO_SETOR_CON = '0335';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (5,'0067','0335','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '6' 
	AND FUK_CO_SETOR_CON = '0335';

	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (6,'0067','0335','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '7'
	AND FUK_CO_SETOR_CON = '0335';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (7,'0067','0335','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '8' 
	AND FUK_CO_SETOR_CON = '0335';

	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (8,'0067','0335','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '9' 
	AND FUK_CO_SETOR_CON = '0335';

	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (9,'0067','0335','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '10' 
	AND FUK_CO_SETOR_CON = '0335';

	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (10,'0067','0335','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '11'
	AND FUK_CO_SETOR_CON = '0335';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (11,'0067','0335','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '12' 
	AND FUK_CO_SETOR_CON = '0335';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (12,'0067','0335','N','N');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '13'
	AND FUK_CO_SETOR_CON = '0335';

	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (13,'0067','0335','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '14'
	AND FUK_CO_SETOR_CON = '0335';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (14,'0067','0335','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '15'
	AND FUK_CO_SETOR_CON = '0335';
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (15,'0067','0335','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '16' 
	AND FUK_CO_SETOR_CON = '0335';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (16,'0067','0335','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '17' 
	AND FUK_CO_SETOR_CON = '0335';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (17,'0067','0335','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '18'
	AND FUK_CO_SETOR_CON = '0335';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (18,'0067','0335','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '19'
	AND FUK_CO_SETOR_CON = '0335';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (19,'0067','0335','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '20' 
	AND FUK_CO_SETOR_CON = '0335';
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (20,'0067','0335','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '21'
	AND FUK_CO_SETOR_CON = '0335';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (21,'0067','0335','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '22' 
	AND FUK_CO_SETOR_CON = '0335';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (22,'0067','0335','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '23' 
	AND FUK_CO_SETOR_CON = '0335';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (23,'0067','0335','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '24' 
	AND FUK_CO_SETOR_CON = '0335';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (24,'0067','0335','N','N');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '25'
	AND FUK_CO_SETOR_CON = '0335';

	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (25,'0067','0335','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '26'
	AND FUK_CO_SETOR_CON = '0335';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (26,'0067','0335','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '27' 
	AND FUK_CO_SETOR_CON = '0335';

	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (27,'0067','0335','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '28' 
	AND FUK_CO_SETOR_CON = '0335';

	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (28,'0067','0335','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '29'
	AND FUK_CO_SETOR_CON = '0335';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (29,'0067','0335','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '30' 
	AND FUK_CO_SETOR_CON = '0335';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (30,'0067','0335','N','N');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '31' 
	AND FUK_CO_SETOR_CON = '0335';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (31,'0067','0335','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '32'
	AND FUK_CO_SETOR_CON = '0335';

	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (32,'0067','0335','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '33'
	AND FUK_CO_SETOR_CON = '0335';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (33,'0067','0335','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '34' 
	AND FUK_CO_SETOR_CON = '0335';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (34,'0067','0335','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '35'
	AND FUK_CO_SETOR_CON = '0335';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (35,'0067','0335','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '36' 
	AND FUK_CO_SETOR_CON = '0335';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (36,'0067','0335','N','N');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '37'
	AND FUK_CO_SETOR_CON = '0335';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (37,'0067','0335','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '38'
	AND FUK_CO_SETOR_CON = '0335';

	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (38,'0067','0335','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '39'
	AND FUK_CO_SETOR_CON = '0335';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (39,'0067','0335','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '40' 
	AND FUK_CO_SETOR_CON = '0335';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (40,'0067','0335','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '41' 
	AND FUK_CO_SETOR_CON = '0335';

	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (41,'0067','0335','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '42'
	AND FUK_CO_SETOR_CON = '0335';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (42,'0067','0335','N','N');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '43' 
	AND FUK_CO_SETOR_CON = '0335';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (43,'0067','0335','N','S');	
		END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '44'
	AND FUK_CO_SETOR_CON = '0335';

	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (44,'0067','0335','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '45'
	AND FUK_CO_SETOR_CON = '0335';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (45,'0067','0335','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '46'
	AND FUK_CO_SETOR_CON = '0335';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (46,'0067','0335','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '47'
	AND FUK_CO_SETOR_CON = '0335';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (47,'0067','0335','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '48' 
	AND FUK_CO_SETOR_CON = '0335';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (48,'0067','0335','N','N');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '1'
	AND FUK_CO_SETOR_CON = '0342';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (1,'0067','0342','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '2' 
	AND FUK_CO_SETOR_CON = '0342';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (2,'0067','0342','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '3' 
	AND FUK_CO_SETOR_CON = '0342';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (3,'0067','0342','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '4'
	AND FUK_CO_SETOR_CON = '0342';

	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (4,'0067','0342','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '5'
	AND FUK_CO_SETOR_CON = '0342';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (5,'0067','0342','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '6' 
	AND FUK_CO_SETOR_CON = '0342';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (6,'0067','0342','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '7'
	AND FUK_CO_SETOR_CON = '0342';

	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (7,'0067','0342','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '8'
	AND FUK_CO_SETOR_CON = '0342';

	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (8,'0067','0342','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '9'
	AND FUK_CO_SETOR_CON = '0342';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (9,'0067','0342','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '10' 
	AND FUK_CO_SETOR_CON = '0342';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (10,'0067','0342','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '11' 
	AND FUK_CO_SETOR_CON = '0342';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (11,'0067','0342','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '12' 
	AND FUK_CO_SETOR_CON = '0342';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (12,'0067','0342','N','N');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '13'
	AND FUK_CO_SETOR_CON = '0342';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (13,'0067','0342','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '14' 
	AND FUK_CO_SETOR_CON = '0342';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (14,'0067','0342','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '15' 
	AND FUK_CO_SETOR_CON = '0342';

	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (15,'0067','0342','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '16' 
	AND FUK_CO_SETOR_CON = '0342';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (16,'0067','0342','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '17' 
	AND FUK_CO_SETOR_CON = '0342';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (17,'0067','0342','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '18'
	AND FUK_CO_SETOR_CON = '0342';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (18,'0067','0342','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '19'
	AND FUK_CO_SETOR_CON = '0342';

	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (19,'0067','0342','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '20' 
	AND FUK_CO_SETOR_CON = '0342';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (20,'0067','0342','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '21'
	AND FUK_CO_SETOR_CON = '0342';

	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (21,'0067','0342','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '22' 
	AND FUK_CO_SETOR_CON = '0342';

	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (22,'0067','0342','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '23' 
	AND FUK_CO_SETOR_CON = '0342';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (23,'0067','0342','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '24'
	AND FUK_CO_SETOR_CON = '0342';

	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (24,'0067','0342','N','N');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '25' 
	AND FUK_CO_SETOR_CON = '0342';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (25,'0067','0342','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '26'
	AND FUK_CO_SETOR_CON = '0342';

	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (26,'0067','0342','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '27'
	AND FUK_CO_SETOR_CON = '0342';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (27,'0067','0342','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '28'
	AND FUK_CO_SETOR_CON = '0342';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (28,'0067','0342','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '29'
	AND FUK_CO_SETOR_CON = '0342';

	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (29,'0067','0342','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '30'
	AND FUK_CO_SETOR_CON = '0342';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (30,'0067','0342','N','N');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '31' 
	AND FUK_CO_SETOR_CON = '0342';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (31,'0067','0342','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '32' 
	AND FUK_CO_SETOR_CON = '0342';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (32,'0067','0342','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '33' 
	AND FUK_CO_SETOR_CON = '0342';

	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (33,'0067','0342','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '34' 
	AND FUK_CO_SETOR_CON = '0342';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (34,'0067','0342','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '35'
	AND FUK_CO_SETOR_CON = '0342';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (35,'0067','0342','N','S');	
	END IF;
	
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '36' 
	AND FUK_CO_SETOR_CON = '0342';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (36,'0067','0342','N','N');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '37'
	AND FUK_CO_SETOR_CON = '0342';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (37,'0067','0342','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '38' 
	AND FUK_CO_SETOR_CON = '0342';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (38,'0067','0342','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '39' 
	AND FUK_CO_SETOR_CON = '0342';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (39,'0067','0342','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '40' 
	AND FUK_CO_SETOR_CON = '0342';

	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (40,'0067','0342','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA
	WHERE FUK_CONFMP = '41'
	AND FUK_CO_SETOR_CON = '0342';

	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (41,'0067','0342','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '42' 
	AND FUK_CO_SETOR_CON = '0342';

	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (42,'0067','0342','N','N');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '43' 
	AND FUK_CO_SETOR_CON = '0342';

	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (43,'0067','0342','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '44' 
	AND FUK_CO_SETOR_CON = '0342';

	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (44,'0067','0342','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '45'
	AND FUK_CO_SETOR_CON = '0342';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (45,'0067','0342','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '46' 
	AND FUK_CO_SETOR_CON = '0342';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (46,'0067','0342','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP)
	INTO vCOUNT 
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '47' 
	AND FUK_CO_SETOR_CON = '0342';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (47,'0067','0342','N','S');	
	END IF;
	
	SELECT COUNT(FUK_CONFMP) 
	INTO vCOUNT
	FROM TB_CONFIG_SETMAPA 
	WHERE FUK_CONFMP = '48' 
	AND FUK_CO_SETOR_CON = '0342';	
	
	IF vCOUNT = 0 THEN 	
		INSERT INTO TB_CONFIG_SETMAPA (FUK_CONFMP, FUK_CO_SETOR, FUK_CO_SETOR_CON, SN_PRD_NATUESTOQ, SN_EXEC_EXTRA) 
		VALUES (48,'0067','0342','N','N');	
	END IF;

 COMMIT; 
END;
/