--CRIAÇÃO DA TABLESPACE
CREATE TABLESPACE EMPRESA LOGGING DATAFILE 'EMPRESA.DBF' SIZE 100M AUTOEXTEND ON NEXT 100M EXTENT MANAGEMENT LOCAL;
--CRIAÇÃO DO USUÁRIO ADMINISTRADOR
CREATE USER ADM_EMPRESA IDENTIFIED BY 123 DEFAULT TABLESPACE EMPRESA QUOTA UNLIMITED ON EMPRESA;
--ACESSO PARA ADM_EMPRESA
GRANT ALL PRIVILEGES TO ADM_EMPRESA;