
--SESSAO 
ALTER SESSION SET CURRENT_SCHEMA=ADM_EMPRESA;

--DROP SEQUENCE
/*
drop sequence "ADM_EMPRESA"."ID_EMPRESA_INCREMENTE";
drop sequence "ADM_EMPRESA"."ID_CLI_EMPRESA_INCREMENTE";
drop sequence "ADM_EMPRESA"."ID_PRODUTO_INCREMENTE";
drop sequence "ADM_EMPRESA"."ID_ESTOQUE_INCREMENTE";
drop sequence "ADM_EMPRESA"."ID_PEDIDO_INCREMENTE";
drop sequence "ADM_EMPRESA"."ID_PED_ITEM_INCREMENTE";
drop sequence "ADM_EMPRESA"."ID_SEGMENTO_INCREMENTE";
*/
--CRIAÇÃO DE SEQUENCE 
CREATE SEQUENCE ID_EMPRESA_INCREMENTE INCREMENT BY 1 START WITH 1 MAXVALUE 9999999999999999999999999999 NOCACHE NOCYCLE;
CREATE SEQUENCE ID_CLI_EMPRESA_INCREMENTE INCREMENT BY 1 START WITH 1 MAXVALUE 9999999999999999999999999999 NOCACHE NOCYCLE;
CREATE SEQUENCE ID_PRODUTO_INCREMENTE INCREMENT BY 1 START WITH 1 MAXVALUE 9999999999999999999999999999 NOCACHE NOCYCLE;
CREATE SEQUENCE ID_ESTOQUE_INCREMENTE INCREMENT BY 1 START WITH 1 MAXVALUE 9999999999999999999999999999 NOCACHE NOCYCLE;
CREATE SEQUENCE ID_PEDIDO_INCREMENTE INCREMENT BY 1 START WITH 1 MAXVALUE 9999999999999999999999999999 NOCACHE NOCYCLE;
CREATE SEQUENCE ID_PED_ITEM_INCREMENTE INCREMENT BY 1 START WITH 1 MAXVALUE 9999999999999999999999999999 NOCACHE NOCYCLE;
CREATE SEQUENCE ID_SEGMENTO_INCREMENTE INCREMENT BY 1 START WITH 1 MAXVALUE 9999999999999999999999999999 NOCACHE NOCYCLE;

--SELECT * FROM USER_SEQUENCES;

--CRIAÇÃO DAS TABELAS
/*
drop table "ADM_EMPRESA"."TB_CAD_SEGMENTO" cascade constraints PURGE;
drop table "ADM_EMPRESA"."TB_CAD_EMPRESA" cascade constraints PURGE;
drop table "ADM_EMPRESA"."TB_CAD_CLIENTE" cascade constraints PURGE;
drop table "ADM_EMPRESA"."TB_PRODUTO" cascade constraints PURGE;
drop table "ADM_EMPRESA"."TB_ESTOQUE_PRD" cascade constraints PURGE;
drop table "ADM_EMPRESA"."TB_PEDIDO" cascade constraints PURGE;
drop table "ADM_EMPRESA"."TB_PEDIDO_ITEM" cascade constraints PURGE;
*/
--CRAETE TABLE 
CREATE TABLE TB_CAD_EMPRESA(
    ID_EMP      NUMBER(10) NOT NULL,
    NOME_EMPRE  VARCHAR2(100) NOT NULL,
    CNPJ        NUMBER NOT NULL,
    ENDERECO    VARCHAR2(100),
    NUM_END     NUMBER,
    TELEFONE    NUMBER,
    FK_ID_SEG	    NUMBER,
    DATA_CAD    DATE DEFAULT SYSDATE,
    OBSERVA     VARCHAR2(150)
    );

CREATE TABLE TB_CAD_SEGMENTO(
	ID_SEG		NUMBER(10) NOT NULL,
	DESC_SEGM	VARCHAR2(50) NOT NULL	
	);

CREATE TABLE TB_CAD_CLIENTE (
    ID_CLI      NUMBER(10) NOT NULL,
    NOME_CLI    VARCHAR2(100) NOT NULL,
    EMAIL       VARCHAR2(100),
    TELEFONE    NUMBER NOT NULL,
    USA_WAPP    CHAR(1) DEFAULT 'N',
    NASC_CLIE   DATE,
    FK_ID_EMP   NUMBER(10),
    OBSERVA     VARCHAR(150)
    );
    
CREATE TABLE TB_PRODUTO(
    ID_COD_PRD  NUMBER(10) NOT NULL,
    NOME_PRD    VARCHAR2(50) NOT NULL,
    DESCRI_PRD  VARCHAR(150),
    TIPO_PRD    VARCHAR(50),
    CLASSIFICA  VARCHAR(50),
    VALIDADE    DATE,
    VALOR_PRD   NUMBER(10,2) DEFAULT 00.0,
    DIVISOR     NUMBER
    );

CREATE TABLE TB_ESTOQUE_PRD(
    ID_EST          NUMBER(10) NOT NULL,
    FK_ID_COD_PRD   NUMBER(10),
    QUANT_ITEM      NUMBER(10),
    TIPO_ITEM       VARCHAR2(10)
    );
    
CREATE TABLE TB_PEDIDO (
    ID_PEDIDO   NUMBER(10) NOT NULL,
    DATA_MOV    DATE,
    HORA_MOV    DATE,
    FK_ID_EMP   NUMBER(10) NOT NULL,
    FK_ID_CLI   NUMBER(10) NOT NULL,
    TOTAL_PED   NUMBER(10,2)
    );
    
CREATE TABLE TB_PEDIDO_ITEM(
    ID_ITE_PED  NUMBER(10) NOT NULL,
    FK_ID_PED   NUMBER(10),
    FK_ID_COD_PRD   NUMBER(10),
    QUANT_ITEM      NUMBER(10),
    VALOR_UNIT      NUMBER(10,2)
    );


--CREATE PRIMARY / FOREING AND UNIQUE KEY CONSTRAINTS
--PRIMARY
ALTER TABLE TB_CAD_EMPRESA ADD CONSTRAINT PK_ID_EMPRESA PRIMARY KEY (ID_EMP);
ALTER TABLE TB_CAD_CLIENTE ADD CONSTRAINT PK_ID_CLIENTE PRIMARY KEY (ID_CLI);
ALTER TABLE TB_PRODUTO ADD CONSTRAINT PK_ID_CODIGO_PRODUTO PRIMARY KEY (ID_COD_PRD);
ALTER TABLE TB_ESTOQUE_PRD ADD CONSTRAINT PK_ID_ESTOQUE_PRODUTO PRIMARY KEY (ID_EST);
ALTER TABLE TB_PEDIDO ADD CONSTRAINT PK_ID_PEDIDO PRIMARY KEY (ID_PEDIDO);
ALTER TABLE TB_PEDIDO_ITEM ADD CONSTRAINT PK_ID_ITEM_PEDIDO PRIMARY KEY (ID_ITE_PED);
ALTER TABLE TB_CAD_SEGMENTO ADD CONSTRAINT PK_ID_ID_SEG PRIMARY KEY (ID_SEG);

--FOREING KEY
ALTER TABLE TB_CAD_CLIENTE ADD CONSTRAINT FK_ID_CAD_EMPRESA FOREIGN KEY (FK_ID_EMP) REFERENCES TB_CAD_EMPRESA(ID_EMP);
ALTER TABLE TB_ESTOQUE_PRD ADD CONSTRAINT FK_ID_CAD_PRODUTO FOREIGN KEY (FK_ID_COD_PRD) REFERENCES TB_PRODUTO(ID_COD_PRD);
ALTER TABLE TB_PEDIDO ADD CONSTRAINT FK_ID_CAD_EMPRPED FOREIGN KEY (FK_ID_EMP) REFERENCES TB_CAD_EMPRESA(ID_EMP);
ALTER TABLE TB_PEDIDO ADD CONSTRAINT FK_ID_CAD_CLIENTE FOREIGN KEY (FK_ID_CLI) REFERENCES TB_CAD_CLIENTE(ID_CLI);
ALTER TABLE TB_PEDIDO_ITEM ADD CONSTRAINT FK_ID_PED_ITEM FOREIGN KEY (FK_ID_PED) REFERENCES TB_PEDIDO(ID_PEDIDO);
ALTER TABLE TB_PEDIDO_ITEM ADD CONSTRAINT FK_ID_COD_PRODUTO FOREIGN KEY (FK_ID_COD_PRD) REFERENCES TB_PRODUTO(ID_COD_PRD);
ALTER TABLE TB_CAD_EMPRESA ADD CONSTRAINT FK_ID_SEG FOREIGN KEY (FK_ID_SEG) REFERENCES TB_CAD_SEGMENTO(ID_SEG);

--UNIQUE
ALTER TABLE TB_CAD_EMPRESA ADD CONSTRAINT UK_NAME_CNPJ UNIQUE (NOME_EMPRE, CNPJ);
ALTER TABLE TB_CAD_CLIENTE ADD CONSTRAINT UK_EMAIL UNIQUE (EMAIL);

--CHECK
ALTER TABLE TB_CAD_CLIENTE ADD CONSTRAINT CK_USA_WAPP CHECK (USA_WAPP IN ('S', 'N'));