--TRIGGER AUTO INCREMENTO 
CREATE OR REPLACE TRIGGER i_CREMENTENT_CAD_SEGMENTO
BEFORE 
    INSERT
ON TB_CAD_SEGMENTO
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
BEGIN 
    IF INSERTING THEN 
        :NEW.ID_SEG := ID_SEGMENTO_INCREMENTE.NEXTVAL;
    END IF;
    EXCEPTION 
        WHEN OTHERS THEN 
            RAISE_APPLICATION_ERROR(-20001,SQLERRM || ' ERRO AO INSERIR CHAVE PRIMARIA ');
END;
/

CREATE OR REPLACE TRIGGER i_CREMENTENT_CAD_EMPRESA
BEFORE 
    INSERT
ON TB_CAD_EMPRESA
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
BEGIN 
    IF INSERTING THEN 
        :NEW.ID_EMP := ID_EMPRESA_INCREMENTE.NEXTVAL;
    END IF;
    EXCEPTION 
        WHEN OTHERS THEN 
            RAISE_APPLICATION_ERROR(-20001,SQLERRM || ' ERRO AO INSERIR CHAVE PRIMARIA ');
END;
/

CREATE OR REPLACE TRIGGER i_CREMENTENT_CLI_EMPRESA
BEFORE 
    INSERT
ON TB_CAD_CLIENTE
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
BEGIN 
    IF INSERTING THEN 
        :NEW.ID_CLI := ID_CLI_EMPRESA_INCREMENTE.NEXTVAL;
    END IF;
    EXCEPTION 
        WHEN OTHERS THEN 
            RAISE_APPLICATION_ERROR(-20001,SQLERRM || ' ERRO AO INSERIR CHAVE PRIMARIA ');
END;
/

CREATE OR REPLACE TRIGGER i_CREMENTENT_PRODUTO
BEFORE 
    INSERT
ON TB_PRODUTO
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
BEGIN 
    IF INSERTING THEN 
        :NEW.ID_COD_PRD := ID_PRODUTO_INCREMENTE.NEXTVAL;
    END IF;
    EXCEPTION 
        WHEN OTHERS THEN 
            RAISE_APPLICATION_ERROR(-20001,SQLERRM || ' ERRO AO INSERIR CHAVE PRIMARIA ');
END;
/

CREATE OR REPLACE TRIGGER i_CREMENTENT_ESTOQUE
BEFORE 
    INSERT
ON TB_ESTOQUE_PRD
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
BEGIN 
    IF INSERTING THEN 
        :NEW.ID_EST := ID_ESTOQUE_INCREMENTE.NEXTVAL;
    END IF;
    EXCEPTION 
        WHEN OTHERS THEN 
            RAISE_APPLICATION_ERROR(-20001,SQLERRM || ' ERRO AO INSERIR CHAVE PRIMARIA ');
END;
/

CREATE OR REPLACE TRIGGER i_CREMENTENT_PEDIDO
BEFORE 
    INSERT
ON TB_PEDIDO
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
BEGIN 
    IF INSERTING THEN 
        :NEW.ID_PEDIDO := ID_PEDIDO_INCREMENTE.NEXTVAL;
    END IF;
    EXCEPTION 
        WHEN OTHERS THEN 
            RAISE_APPLICATION_ERROR(-20001,SQLERRM || ' ERRO AO INSERIR CHAVE PRIMARIA ');
END;
/

CREATE OR REPLACE TRIGGER i_CREMENTENT_PEDIDO_ITE
BEFORE 
    INSERT
ON TB_PEDIDO_ITEM
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
BEGIN 
    IF INSERTING THEN 
        :NEW.ID_ITE_PED := ID_PED_ITEM_INCREMENTE.NEXTVAL;
    END IF;
    EXCEPTION 
        WHEN OTHERS THEN 
            RAISE_APPLICATION_ERROR(-20001,SQLERRM || ' ERRO AO INSERIR CHAVE PRIMARIA ');
END;
/